config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  root to: 'events#index'

  resources :users, only: [:show, :edit, :update]

  resources :events do
    resources :photos, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]

    resources :subscriptions, only: [:create, :destroy]
    post :show, on: :member
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

  validates  :event, presence: true
  validates :body, presence: true

  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event , only: %i[create destroy]
  before_action :set_comment, only: %i[  destroy ]



   def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if @new_comment.save
      redirect_to @event, notice: I18n.t("controllers.comments.created")
    else
      render "events/show", alert: I18n.t("controllers.comments.errors.creating")
    end
  end

  def destroy
    message = { notice: I18n.t("controllers.comments.destroyed") }

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = { alert: I18n.t("controllers.comments.errors.deleting") }
    end

    redirect_to @event, message
  end

  private

    def set_event
      @event = Event.find(params[:event_id])
    end

    def set_comment
      @comment = @event.comments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_name)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="buffer-bottom">
  <p><%= comment.body %></p>
  <p>
    <span>
      <% if comment.user.present? %>
        <%= render partial: "users/user", object: comment.user %>
      <% else %>
        <em><strong><%= comment.user_name %></strong></em>
      <% end %>
    </span>
    <em class="registration-label"><%= l comment.created_at, format: :short %></em>

     <div class="align-self-end ms-auto p-2 bd-highlight">
      <% if current_user_can_edit?(comment) %>
        <div class="buffer-top mt-0">
          <%= button_to t('app.delete'), event_comment_path(comment.event, comment), class: 'btn btn-danger text-sm',
                        method: :delete, data: { confirm: t(".destroy_confirm")} %>
        </div>
      <% end %>
    </div>
    </p>
</div>

app/views/comments/_form.html.erb
<%= form_for [@event, comment] do |f| %>
    <%= render partial: "partials/form_errors", locals: {model: comment} %>

    <div class="form-group mb-2">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control" %>
    </div>

    <% unless user_signed_in? %>
        <div class="form-group mb-2">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: "form-control" %>
        </div>
    <% end %>

    <div class="actions mb-2">
      <%= f.submit "Отправить", class: "btn btn-primary" %>
    </div>
<% end %>