config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  root to: 'events#index'

  resources :users, only: [:show, :edit, :update]

  resources :events do
    resources :photos, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]

    resources :subscriptions, only: [:create, :destroy]
    post :show, on: :member
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :comments
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user

  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[show]
  before_action :set_current_user_event, only: %i[edit update destroy]

  def index
    @events = Event.all
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event =  current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4">
  <div class="card thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="card-body">
        <div class="event-description">
          <div class="card-title">
            <h3><%= link_to event.title, event_path(event) %></h3>
          </div>

          <div class="card-text">
            <h4><small><%= l event.datetime, format: :short %></small></h4>
            <div class="mt-2"><%= event.address %></div>
          </div>

          <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <%= render partial: "partials/form_errors", locals: {model: @event} %>
  <div class="mt-2">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mt-2">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="mt-2">
    <%= form.label :datetime %>
    <p><%= form.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="mt-2">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mt-2">
    <%= form.submit 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 mt-2">
    <%= render 'form', event: @event %>
  </div>
</div>
</div>

app/views/events/index.html.erb
<h1>События</h1>

<div class="my-4">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
</div>

<div class="row mb-2">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Создание события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form', event: @event %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row mt-2 m-1">
    <div class="col-md-12">
      <%= content_tag "div", "", class: "event-background",
        style: "background-image: url(#{event_photo(@event)})" %>
      <div class="event-info-inner row">
        <div class="col-md-6">

          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3><small><%= link_to @event.address,
                "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-both mb-2 mt-2">
              <%= link_to 'Изменить', edit_event_path(@event),
              class: 'btn btn-primary' %>
            </div>

            <div class="buffer-both mb-2 mt-2">
              <%= button_to 'Удалить', event_path(@event), method: :delete,
                  form: { data: { turbo_confirm: I18n.t(:delete_message) }},
                  class: 'btn btn-primary' %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
   <div class="col-md-6">

        <div class="event-photo-form">
        <%= render partial: "photos/form", locals: {photo: @new_photo || @event.photos.build} %>
        </div>

        <div class="event-photos row buffer-both">
        <div class="event-photos-gallery">
          <%= render partial: "photos/photo", collection: @event.photos.except(@new_photo) %>
        </div>
      </div>

    <div class="event-comments buffer-top">
        <%= render partial: "comments/form",
          locals: { comment: @new_comment || @event.comments.build } %>

        <div class="buffer-both">
          <%= render partial: "comments/comment",
            collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

      <div class="col-md-6">
        <div class="event-owner mb-2 mt-2">
        <h4>Зовет:</h4>
          <p><%= render partial: "users/user", object: @event.user %></p>
        </div>

      <div class="event-subscriptions">
        <% if @event.subscriptions.except(@new_subscription).any? %>
          <h4>Пойдут:</h4>
          <div>
            <p><%= render partial: "subscriptions/subscription",
              collection: @event.subscriptions.except(@new_subscription) %>
            </p>
          </div>
        <% end %>
      </div>

      <% unless @event.user == current_user %>
        <div class="event-subscription-form ">
          <h4>Я пойду:</h4>
          <div>
            <%= render partial: "subscriptions/form", locals: {
              subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>