config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  root to: 'events#index'

  resources :users, only: [:show, :edit, :update]

  resources :events do
    resources :photos, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]

    resources :subscriptions, only: [:create, :destroy]
    post :show, on: :member
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :event, presence: true
  validates :user, presence: true
  validates :photo, presence: true

  scope :persisted, -> { where "id IS NOT NULL" }

  mount_uploader :photo, PhotoUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_photo, only: [:destroy]

  def create
    @new_photo = @event.photos.build(photo_params)

    @new_photo.user = current_user

    if @new_photo.save
      redirect_to @event, notice: I18n.t("controllers.photos.created")
    else
      render "events/show", alert: I18n.t("controllers.photos.error")
    end
  end

  def destroy
  message = { notice: I18n.t("controllers.photos.destroyed") }

    if current_user_can_edit?(@photo)

      @photo.destroy
    else
      message = { alert: I18n.t("controllers.photos.error") }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end
end

app/views/photos/_form.html.erb
<%= form_for [@event, photo], html: { multipart: true } do |f| %>
  <%= render partial: "partials/form_errors", locals: { model: photo } %>

  <div class="form-group mb-2 mt-2">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: "mb-2" %>
  </div>

  <div class="actions m-3">
    <%= f.submit "Загрузить", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div class="row mt-2 ">
  <div class=" col-sm-8 ">
    <%= image_tag photo.photo.url , class:"img-thumbnail" %>
  </div>

  <div class="col-sm-4">
    <div >
      <a href="<%= user_path(photo.user) %>">
        <img src="<%= user_avatar(photo.user) %>" class="img-icon rounded-circle">
      </a>
    </div>

    <p>
      <a href="<%= user_path(photo.user) %>"><%= photo.user.name %></a>
    </p>
  </div>

  <% if current_user_can_edit?(photo) %>
    <%= button_to I18n.t("app.delete"), event_photo_path(photo.event, photo), method: :delete, class: "btn btn-danger mt-2",
      form: { data: { turbo_confirm: I18n.t("actions.confirmation") }} %>
  <% end %>
</div>